architect:
  - javacoded78
assets:
  settings.xml: javacoded78/secrets#assets/settings.xml
  secring.gpg: javacoded78/secrets#assets/Andrei Soroka_0x872A42FB_SECRET.gpg
  pubring.gpg: javacoded78/secrets#assets/Andrei Soroka_0x872A42FB_public.gpg
docker:
  image: l3r8y/rultor-image:1.0.3
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -DskipTests -P release --errors --settings ../settings.xml